In [17]:
import os

In [18]:
import numpy as np

In [19]:
import matplotlib.pylab as plt

In [20]:
from PIL import Image

In [65]:
array=np.zeros([200,200])

In [60]:
re_img=[]

In [61]:
rootDir="photos"

In [84]:
for dirName,subdirlist,fileList in os.walk(rootDir):
    print('Found directory:%s' %dirName)
    for fname in fileList:
        print('file name: /t%s' %fname)
        #print('Found directory: %s' %dirName)
        i=Image.open(dirName + "/" + fname)
        resize=i.resize((200,200))
        np_re_img=np.array(resize)
        re_img.append(np_re_img)

Found directory:photos
file name: /t1.jpg
file name: /t10.jpg
file name: /t2.jpg
file name: /t3.jpg
file name: /t4.jpg
file name: /t5.jpg
file name: /t6.jpg
file name: /t7.jpg
file name: /t8.jpg
file name: /t9.jpg


In [81]:
array=np.array(re_img)

In [82]:
print(array)
print(f"Array shape:(array.shape)")

[[[[ 55  62  81]
   [ 54  61  80]
   [ 53  60  79]
   ...
   [ 38  53  74]
   [ 38  53  74]
   [ 37  53  69]]

  [[ 56  63  81]
   [ 55  62  80]
   [ 53  60  78]
   ...
   [ 38  53  74]
   [ 38  53  74]
   [ 37  53  69]]

  [[ 58  65  83]
   [ 56  63  81]
   [ 55  62  80]
   ...
   [ 38  53  74]
   [ 38  53  74]
   [ 38  54  70]]

  ...

  [[ 47  28  11]
   [ 42  24   4]
   [ 38  20   0]
   ...
   [100  71  15]
   [101  74  21]
   [ 98  74  26]]

  [[ 48  31  13]
   [ 41  24   4]
   [ 38  21   1]
   ...
   [ 94  63   8]
   [ 91  61   9]
   [ 88  64  16]]

  [[ 46  31  12]
   [ 39  24   5]
   [ 38  23   2]
   ...
   [ 88  55   2]
   [ 82  50   1]
   [ 83  60  10]]]


 [[[ 57  19  10]
   [ 61  23  14]
   [ 43   5   0]
   ...
   [ 74  67  13]
   [ 85  77  28]
   [ 57  48   7]]

  [[ 57  17   9]
   [ 48   8   0]
   [ 68  28  20]
   ...
   [ 56  49   0]
   [ 24  17   0]
   [ 89  80  39]]

  [[ 38   0   0]
   [ 54  11   4]
   [ 38   0   0]
   ...
   [102  96  36]
   [ 80  73  19]
   [177 170